name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude:
    # Only run when a comment starts with /claude or on PR events
    if: |
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/claude')) ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Add custom prompt for BAML-specific context
          claude_args: |
            --read .claude/CLAUDE.md
            --read baml-codegen/SKILL.md
